 Actor / Film CMS schema
-- Safe to run multiple times.

begin;

-- ===========================================
-- 0) Rename old table if still present
-- ===========================================
do $$
begin
  if to_regclass('public."filmReleases"') is null
     and to_regclass('public."musicReleases"') is not null then
    alter table public."musicReleases" rename to "filmReleases";
  end if;
end $$;

-- ===========================================
-- 1) Filmography projects (replaces music releases)
-- ===========================================
create table if not exists public."filmReleases" (
  id bigint generated by default as identity primary key,
  year text not null,
  title text not null,
  role text not null,
  poster text not null default 'Media/Brandon_Sklenar.jpg',
  "trailerUrl" text not null default '',
  created_at timestamptz not null default now()
);

-- Add missing columns for upgraded databases.
alter table public."filmReleases" add column if not exists role text;
alter table public."filmReleases" add column if not exists poster text;
alter table public."filmReleases" add column if not exists "trailerUrl" text;
alter table public."filmReleases" alter column poster set default 'Media/Brandon_Sklenar.jpg';
alter table public."filmReleases" alter column "trailerUrl" set default '';

-- Migrate old column values when present.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'filmReleases' and column_name = 'type'
  ) then
    execute 'update public."filmReleases" set role = coalesce(role, type, ''Unknown Role'') where role is null or role = ''''';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'filmReleases' and column_name = 'cover'
  ) then
    execute 'update public."filmReleases" set poster = coalesce(poster, cover, ''Media/Brandon_Sklenar.jpg'') where poster is null or poster = ''''';
  end if;
end $$;

update public."filmReleases" set role = 'Unknown Role' where role is null or role = '';
update public."filmReleases" set poster = 'Media/Brandon_Sklenar.jpg' where poster is null or poster = '';
update public."filmReleases" set "trailerUrl" = '' where "trailerUrl" is null;

alter table public."filmReleases" alter column role set not null;
alter table public."filmReleases" alter column poster set not null;
alter table public."filmReleases" alter column "trailerUrl" set not null;

-- Remove legacy columns once migrated.
alter table public."filmReleases" drop column if exists type;
alter table public."filmReleases" drop column if exists cover;

-- ===========================================
-- 2) Acting projects
-- ===========================================
create table if not exists public."actingProjects" (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  video text not null,
  link text not null default '#',
  created_at timestamptz not null default now()
);

-- ===========================================
-- 3) Gallery items
-- ===========================================
create table if not exists public."galleryItems" (
  id bigint generated by default as identity primary key,
  src text not null,
  title text not null,
  category text not null,
  created_at timestamptz not null default now()
);

-- ===========================================
-- 4) Team members
-- ===========================================
create table if not exists public."teamMembers" (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  bio text not null,
  image text not null,
  skills jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- ===========================================
-- 5) Contact messages
-- ===========================================
create table if not exists public."contactMessages" (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  "timestamp" bigint,
  created_at timestamptz not null default now()
);

-- ===========================================
-- 6) Grants
-- ===========================================
grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on public."filmReleases" to anon, authenticated;
grant select, insert, update, delete on public."actingProjects" to anon, authenticated;
grant select, insert, update, delete on public."galleryItems" to anon, authenticated;
grant select, insert, update, delete on public."teamMembers" to anon, authenticated;
grant select, insert, update, delete on public."contactMessages" to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

-- ===========================================
-- 7) RLS + Policies
-- ===========================================
alter table public."filmReleases" enable row level security;
alter table public."actingProjects" enable row level security;
alter table public."galleryItems" enable row level security;
alter table public."teamMembers" enable row level security;
alter table public."contactMessages" enable row level security;

drop policy if exists "anon_all" on public."filmReleases";
drop policy if exists "music_all" on public."filmReleases";
drop policy if exists "film_all" on public."filmReleases";
create policy "film_all"
on public."filmReleases"
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "acting_all" on public."actingProjects";
create policy "acting_all"
on public."actingProjects"
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "gallery_all" on public."galleryItems";
create policy "gallery_all"
on public."galleryItems"
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "team_all" on public."teamMembers";
create policy "team_all"
on public."teamMembers"
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "contact_all" on public."contactMessages";
create policy "contact_all"
on public."contactMessages"
for all
to anon, authenticated
using (true)
with check (true);

commit;
