-- 🏗️ COMPLETE SUPABASE SCHEMA - All Tables + RLS + Sample Data
-- Run this SINGLE script in Supabase SQL Editor (replaces setup.sql + update.sql)
-- Creates ALL tables from project analysis + grants

-- =================================
-- 🔧 CLEANUP (Drop existing)
-- =================================
DROP TABLE IF EXISTS public.newsletterSubscribers, public.contactMessages, public.teamMembers, public.galleryItems, public.actingProjects, public."filmReleases" CASCADE;

-- =================================
-- 1️⃣ FILM RELEASES
-- =================================
CREATE TABLE public."filmReleases" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  year TEXT NOT NULL,
  role TEXT NOT NULL,
  poster TEXT NOT NULL DEFAULT 'Media/Brandon_Sklenar.jpg',
  "trailerUrl" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sample data
INSERT INTO public."filmReleases" (title, year, role, poster, "trailerUrl") VALUES
('John Star', '2025', 'Lead Actor', 'Media/Brandon_Sklenar.jpg', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
('Mapplethorpe', '2018', 'Edward Mapplethorpe', 'Media/Brandon_Sklenar.jpg', ''),
('Vice', '2018', 'Bobby Prentace', 'Media/Brandon_Sklenar.jpg', '');

-- =================================
-- 2️⃣ ACTING PROJECTS  
-- =================================
CREATE TABLE public."actingProjects" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  video TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '#',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public."actingProjects" (title, description, video, link) VALUES
('1923 Trailer', 'Spencer Dutton - Yellowstone prequel', 'dQw4w9WgXcQ', '#'),
('Midway Scene', 'George H. Gay Jr. - WWII film', 'abc123', 'https://imdb.com/title/tt4158496');

-- =================================
-- 3️⃣ GALLERY ITEMS
-- =================================
CREATE TABLE public."galleryItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  src TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public."galleryItems" (src, title, category) VALUES
('public/gallery/media/1773049456123-c631d9cabd395a806622174370e54f2e.jpg', 'On Set', 'Film'),
('public/gallery/media/1773052018888-34f0c8f87c32d6a32a410cf573b43f91.jpg', 'Premiere', 'Event');

-- =================================
-- 4️⃣ TEAM MEMBERS
-- =================================
CREATE TABLE public."teamMembers" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  bio TEXT,
  image TEXT DEFAULT 'Media/Brandon_Sklenar.jpg',
  skills TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public."teamMembers" (name, role, bio, skills) VALUES
('Jane Doe', 'Manager', '15+ years entertainment', ARRAY['Negotiations', 'Bookings']),
('John Smith', 'Photographer', 'Film set specialist', ARRAY['Portrait', 'Action']);

-- =================================
-- 5️⃣ CONTACT MESSAGES (append-only)
-- =================================
CREATE TABLE public."contactMessages" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  ip INET,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =================================
-- 6️⃣ NEWSLETTER SUBSCRIBERS
-- =================================
CREATE TABLE public."newsletterSubscribers" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

-- =================================
-- 🔒 RLS + POLICIES (Public read, Admin write)
-- =================================
-- Enable RLS on all tables
ALTER TABLE public."filmReleases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."actingProjects" ENABLE ROW LEVEL SECURITY;  
ALTER TABLE public."galleryItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."teamMembers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contactMessages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."newsletterSubscribers" ENABLE ROW LEVEL SECURITY;

-- Public: SELECT only
CREATE POLICY "Public read filmReleases" ON public."filmReleases" FOR SELECT USING (true);
CREATE POLICY "Public read actingProjects" ON public."actingProjects" FOR SELECT USING (true);
CREATE POLICY "Public read galleryItems" ON public."galleryItems" FOR SELECT USING (true);
CREATE POLICY "Public read teamMembers" ON public."teamMembers" FOR SELECT USING (true);

-- Contact + Newsletter: Public INSERT (forms), Admin SELECT+DELETE
CREATE POLICY "Public insert contact" ON public."contactMessages" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert newsletter" ON public."newsletterSubscribers" FOR INSERT WITH CHECK (true);

-- Admin full access (service_role bypasses RLS)

-- =================================
-- ⚙️ INDEXES + GRANTS
-- =================================
-- Indexes for performance
CREATE INDEX idx_contact_created ON public."contactMessages"(created_at);
CREATE INDEX idx_newsletter_email ON public."newsletterSubscribers"(email);

-- Grants
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO authenticated, anon;

-- =================================
-- ✅ SUCCESS CHECK
-- =================================
SELECT 
  '✅ ALL TABLES CREATED!' as status,
  (SELECT COUNT(*) FROM public."filmReleases") as films,
  (SELECT COUNT(*) FROM public."actingProjects") as acting,
  (SELECT COUNT(*) FROM public."galleryItems") as gallery,
  (SELECT COUNT(*) FROM public."teamMembers") as team;

-- Ready! Update .env.local with service_role key → npm run dev
